export const Colors = {
  Primary_BG_Color: '#F9FBFB',
  label_text: '#627483',
  welcome_text: '#091D2F',
  role_BG_Color: '#FFFFFF',
  selected_role_color: '#34B1E4',
  deselected_role_color: '#DCE6EF',
  btn_color: '#004B87',
  next_btn: '#004B87',
  border_color: '#E1E6EA',
  placeholder_color: '#ACB4C8',
  forgot_psw: '#00B4DD',
  darkest_blue: '#0B152D',
  index_Bg_color: '#EEF4F6',
  sub_process: '#7F8697',
  ProgessBar_BG_Color: '#EFF1F5',
  profile_text: '#555C6F',
  Header_Text_Color: '#9EAAB3',
  ProgressBar_Line_Color: '#75BB59',
  input_Text_Color: '#464C5C',
  Detail_input_heading: '#929BB2',
  Detail_input_Color: '#EDF2F2',
  Detail_input_Text_Color: '#646B7D',
  white_color: '#FFFFFF',
  other_BG_Color: '#E8E8E8',
  brochures_text: '#4C545C',
  selectedItem: '#F5FDFF',
};
