require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'StickXFit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNSound', :path => '../node_modules/react-native-sound'


  pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'

  target 'StickXFitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
